### PR TITLE
Ft eeprom read

### PR DESCRIPTION
**Pull request by krister-ts**

### CODE REVIEW

**Review by snmishra — COMMENTED** [review]
Looks mostly alright other than the `cast` use

**Comment by krister-ts** [comment]
> Looks mostly alright other than the `cast` use

I was getting an exception on the type because the string buffer was not c_char_p. Maybe I will check again that it doesn't work directly and let you know.

**Comment by snmishra** [comment]
@krister-ts It might be nice to support other devices for `FT_EEPROM_Read`. In #57, added all the structures (in structs.py) and constants (in defines.py) that were listed in D2XX programming guide. Please see if that helps?

Correct me if I'm wrong, but I think your current definition only works on Windows. It may be good have the structures in a platform-independent module.

**Comment by krister-ts** [comment]
@snmishra Yes, there is a lot of repeated code across these modules that can be pooled together. We should have a common module. Maybe add _ftd2xx_win32 and make _ftd2xx the common??

**Pull request closed without merging**
