### PR TITLE
Add asynchronous support

### PR DESCRIPTION
**Pull request by krister-ts**
I would like to add support for `asyncio` to open the door for running multiple devices concurrently.

### CODE REVIEW

**Comment by krister-ts** [comment]
Retry DeepCode

**Comment by snmishra** [comment]
@krister-ts Thanks a lot for the contribution. I don't have a way to test the changes. Have you run the tests?

**Comment by krister-ts** [comment]
I have tested the FTD2XX class in aio that I needed. I'm confident the 'classic' (synchronous) one should be working still.

**Comment by snmishra** [comment]
Awesome! Thanks, merged.

**Comment by krister-ts** [comment]
Could you push this pypi? I noticed the even the stime work-around is only in the master. It would be nice to have a working version for linux that I could put in requirements (instead of git+http://....).

**Comment by snmishra** [comment]
Thanks for the push @krister-ts . Released as [1.2.0b2 on PyPI](https://pypi.org/manage/project/ftd2xx/release/1.2.0b2/)

**Comment by krister-ts** [comment]
You rock!

**Pull request merged**
