### PR TITLE
Type hints

### PR DESCRIPTION
**Pull request by snmishra**
Add type hints and fix bugs found by type checking

### CODE REVIEW

**Review by krister-ts — APPROVED** [review]
Great work! I like that you added the logger there.

**Comment by snmishra** [comment]
@krister-ts So merge and release?

**Comment by krister-ts** [comment]
Have you run the tests? I can install and run if not.

**Comment by krister-ts** [comment]
I have a `FileNotFoundError` from `import ftd2xx`

**Comment by snmishra** [comment]
> 
> 
> I have a `FileNotFoundError` from `import ftd2xx`
> 
> The extra_dll code block (_ftd2xx.py) removed fixes it for me.

Interesting. I couldn't install the driver for some reason and Python 3.8 requires explicit addition of non-standard DLL directories.

I'll leave the extra_dll_dir as commented code in case some one needs it.

**Review by krister-ts — APPROVED** [review]
Pytest passed. Looks like it is good to release.

**Pull request merged**
